#!/usr/bin/env bash
# Set up desktop-free kiosk boot: tty1 autologin -> startx -> cast app.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USER_NAME="${SUDO_USER:-$USER}"
USER_HOME="$(eval echo "~$USER_NAME")"

if [[ "$USER_NAME" == "root" ]]; then
  echo "Run as your normal user (not root): ./scripts/install_service.sh"
  exit 1
fi

echo "=== Installing X packages (xinit, Xorg) ==="
sudo apt-get install -y xinit xserver-xorg x11-xserver-utils

for cmd in xinit startx Xorg; do
  if ! command -v "$cmd" >/dev/null; then
    echo "ERROR: $cmd not found after apt install"
    exit 1
  fi
done

if [[ ! -x "$APP_DIR/.venv/bin/python" ]]; then
  echo "ERROR: venv missing at $APP_DIR/.venv"
  echo "  python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"
  exit 1
fi

chmod +x "$APP_DIR/scripts/start_app.sh" \
         "$APP_DIR/scripts/enable_fast_boot.sh" \
         "$APP_DIR/scripts/restore_desktop.sh" \
         "$APP_DIR/scripts/diagnose_boot.sh"

echo "=== Removing any old systemd unit (X can't own a VT from a service) ==="
sudo systemctl disable --now pi-audio-cast-display.service 2>/dev/null || true
sudo rm -f /etc/systemd/system/pi-audio-cast-display.service
sudo systemctl daemon-reload 2>/dev/null || true

echo "=== Configuring fast boot + tty1 autologin ==="
sudo "$APP_DIR/scripts/enable_fast_boot.sh" "$USER_NAME"

echo "=== Writing $USER_HOME/.xinitrc (runs the cast app) ==="
cat > "$USER_HOME/.xinitrc" <<EOF
#!/bin/sh
# Auto-generated by install_service.sh — launches the Pi Audio Cast Display.
exec "$APP_DIR/scripts/start_app.sh"
EOF
chmod +x "$USER_HOME/.xinitrc"

echo "=== Adding startx-on-login guard to $USER_HOME/.bash_profile ==="
PROFILE="$USER_HOME/.bash_profile"
MARKER="# >>> pi-audio-cast-display startx >>>"
if ! grep -qF "$MARKER" "$PROFILE" 2>/dev/null; then
  cat >> "$PROFILE" <<EOF

$MARKER
if [ -z "\${DISPLAY:-}" ] && [ "\${XDG_VTNR:-}" = "1" ]; then
  exec startx
fi
# <<< pi-audio-cast-display startx <<<
EOF
  echo "  appended startx guard"
else
  echo "  startx guard already present"
fi

echo ""
echo "=== Kiosk boot configured ==="
echo "Default target: $(systemctl get-default)"
echo "tty1 autologin: $USER_NAME"
echo "App entry:      $USER_HOME/.xinitrc -> $APP_DIR/scripts/start_app.sh"
echo ""
echo "Reboot to test: sudo reboot"
echo "Restore desktop: sudo $APP_DIR/scripts/restore_desktop.sh"
